---
title: "R Notebook"
output: html_notebook
---



```{r}
library(data.table)
library(dplyr)
```

```{r}

annotatacao <- fread(file = '/Users/josedias/Documents/PhD_Cologne/projects/PopAmaranth/popamabrowser/data/Ahyp_preparation', fill = TRUE, sep = ";", header = T) %>%
  select(-c(V1))

ids <- fread(file = '/Users/josedias/Documents/PhD_Cologne/projects/PopAmaranth/popamabrowser/data/ids_only' )

gff_file<- fread(file= '/Users/josedias/Documents/PhD_Cologne/projects/PopAmaranth/popamabrowser/data/Ahypochondriacus_459_v2.1.gene.gff3.gz')

identification <- fread(file = '/Users/josedias/Documents/PhD_Cologne/projects/PopAmaranth/popamabrowser/data/IDs', header = FALSE ) %>%
  rename(transcriptName=V1)

juntos<-annotatacao %>%
full_join(identification, by = "transcriptName") %>%
  fwrite('/Users/josedias/Documents/PhD_Cologne/projects/PopAmaranth/data/processed/juntos', sep =";", quote = F)

gff_file %>%
  filter(V3=='gene')

together<- fread(file = '/Users/josedias/Documents/PhD_Cologne/projects/PopAmaranth/data/processed/juntos_corrigidos', sep = "\t" )

new_gff<-
paste0(gff_file$V9, together$`locus_name=locusName;transcriptName=transcriptName;Pfam=Pfam;Panther=Panther;KOG=KOG;EC=ec;KO=KO;GO=GO;Best-hit-arabi-name=Best-hit-arabi-name;arabi-symbol=arabi-symbol;arabi-defline=arabi-defline`)


gff_file$V9<-paste(gff_file$V9, together$`locus_name=locusName;transcriptName=transcriptName;Pfam=Pfam;Panther=Panther;KOG=KOG;EC=ec;KO=KO;GO=GO;Best-hit-arabi-name=Best-hit-arabi-name;arabi-symbol=arabi-symbol;arabi-defline=arabi-defline`)

gff_file

#gff_fixed<- fwrite(gff_file, '/Users/josedias/Documents/PhD_Cologne/projects/PopAmaranth/popamabrowser/data/gff_file', quote = F, sep="\t")


```

