---
title: "R Notebook"
output: html_notebook
---



```{r}

library(data.table)
library(RcppCNPy)
library("factoextra")
library('ggfortify')
library('cowplot')
library('dplyr')
library(ggpubr)
library('patchwork')
library(wesanderson)
library(ggsci)

```


```{r}

nice_layout<-   theme_cowplot()+
    panel_border(color = "grey85", size = 1, linetype = 1,
  remove = FALSE, "black")



# teste_selection <- npyLoad("/Users/josedias/mount/projects/scratch/jgd/outputs/fixed_GRE.selection.npy")
#
# teste_admix <- npyLoad("/Users/josedias/mount/projects/scratch/jgd/outputs/fixed_GRE.admix.Q.npy")
#
# teste_inbeed <- npyLoad("/Users/josedias/mount/projects/scratch/jgd/outputs/fixed_GRE.inbreed.npy")

covaraiants<- fread('/Users/josedias/mount/projects/ag-stetter/jdias/projects/Genome_browser/data/covariantes_data.cov')

Species<-c(rep('A. caudatus', 28), rep('A. cruentus', 21), rep('A. hybridus', 9),  rep('A. hypochondriacus', 18), rep('A. quitensis', 12))

PCS<-prcomp(covaraiants)
PCS$rotation[,2]
identification<- fread('/Users/josedias/mount/projects/ag-stetter/jdias/projects/Genome_browser/data/sampleID_AmaranthGDB', header = F)

grafico<- autoplot(prcomp(covaraiants)) +
  geom_point(aes(color=minhas_cores)) +
  nice_layout +
#  scale_color_manual(values=ggsc(n=3, name="Darjeeling"))
 scale_fill_discrete(name = Species, labels = Species)
grafico



pc1_2<- ggplot(PCS, aes(PCS$x[,1],PCS$x[,2]))+
    geom_point(aes(color=Species),  shape = 19, size = 3 , alpha = 0.55) +
  xlab("PC 1 (65.16%)") +
  ylab("PC 2 (28.82%)") +
  nice_layout +
  # theme(legend.title = element_text(size = 15),
  #       legend.text = element_text(size = 15))
  scale_fill_manual(values=c('#33A02C', '#A6CEE3', '#FF7F00', '#FB9A99', '#CAB2D6')) +
  scale_color_manual(values=c('#33A02C', '#A6CEE3', '#FF7F00', '#FB9A99', '#CAB2D6'))

pc1_2



pc2_3<- ggplot(PCS, aes(PCS$x[,1],PCS$x[,3]))+
      geom_point(aes(color=Species), shape = 19, size = 3, , alpha = 0.55)  +
  xlab("PC 1 (65.16%)") +
  ylab("PC 3 (1.62%)") +
  nice_layout +
  scale_fill_manual(values=c('#33A02C', '#A6CEE3', '#FF7F00', '#FB9A99', '#CAB2D6')) +
  scale_color_manual(values=c('#33A02C', '#A6CEE3', '#FF7F00', '#FB9A99', '#CAB2D6'))



pc2_3


pc_plots<-ggarrange(pc1_2  , pc2_3, legend="none")
pc_plots
ggsave("/Users/josedias/Desktop/pca_plots_side.png", pc_plots,  dpi = 300,   device = "png", height = 4)

# ggsave(grafico, filename = '/Users/josedias/Desktop/grafico_pca_all_samples.pdf' )

pcs_

combined<-  pc1_2 + pc2_3 + plot_layout(guides = "collect") & theme(legend.position = "bottom",   legend.key.size =2)


 mx<-prcomp(covaraiants)
vars <- apply(mx$x, 2, var)

Variation<-(vars/sum(vars))*100
varaibles<-Variation[1:10]

write.csv(varaibles, "/Users/josedias/Desktop/Variance_10PCs.txt", sep = '\t', quote = FALSE)



theme
```



```{r, echo=FALSE, results='hide'}
# res.pca <- prcomp(iris[, -5],  scale = TRUE)

```



```{r}

library('ggfortify')

PCS<-prcomp(covaraiants)


PCS$rotation[,2]

identification<- fread('/Users/josedias/mount/projects/ag-stetter/jdias/projects/Genome_browser/data/sampleID_AmaranthGDB', header = F)

grafico<- autoplot(prcomp(covaraiants)) +
  geom_point(aes(color=Species)) +
  nice_layout
# scale_fill_discrete(name = "Species", labels = species)
grafico




pc1_2<- ggplot(PCS, aes(PCS$x[,1],PCS$x[,2]))+
    geom_point(aes(color=Species),alpha =0.3,  shape = 19, size = 3) +
  xlab("PC 1 (65.16%)") +
  ylab("PC 2 (28.82%)") +
  nice_layout +
  theme(legend.title = element_text(size = 15),
        legend.text = element_text(size = 15))

pc1_2
pc2_3<- ggplot(PCS, aes(PCS$x[,1],PCS$x[,3]))+
      geom_point(aes(color=Species),alpha =0.3,  shape = 19, size = 3)  +
  xlab("PC 1 (65.16%)") +
  ylab("PC 3 (1.62%)") +
  nice_layout

pc2_3


pc_plots<-ggarrange(pc1_2  , pc2_3, common.legend = TRUE, legend="bottom")
pc_plots
ggsave("/Users/josedias/Desktop/pca_plots_side.png", pc_plots,  dpi = 300,   device = "png", height = 4)

# ggsave(grafico, filename = '/Users/josedias/Desktop/grafico_pca_all_samples.pdf' )

pcs_10<-as.data.frame(PCS$x[,1:10])
pcs_10<-cbind(identification,pcs_10)


pcs_10$row_name=identification

pcs_10 %>%
  rename(SampleID=V1)
# fwrite("/Users/josedias/mount/projects/ag-stetter/jdias/projects/Genome_browser/all_species_PC10.txt", sep="\t")


combined<-  pc1_2 + pc2_3 + plot_layout(guides = "collect") & theme(legend.position = "bottom",   legend.key.size =2)




mx<-prcomp(covaraiants)
vars <- apply(mx$x, 2, var)

Variation<-(vars/sum(vars))*100
varaibles<-Variation[1:10]

write.csv(varaibles, "/Users/josedias/Desktop/Variance_10PCs.txt", sep = '\t', quote = FALSE)

```
