---
title: "final Comparison SFS plots"
output: html_notebook
---


```{r, results="hide", echo =FALSE}
library('cowplot')
library(data.table)
library(dplyr)
library(ggplot2)


nice_layout<-   theme_cowplot()+
    panel_border(color = "grey85", size = 1, linetype = 1,
  remove = FALSE, "black") 
```

```{r, results="hide", echo =FALSE, eval =FALSE}
cruenuts_AF<-fread('/Users/josedias/mount/scratch/jgoncal1/outputs/cruentus.mafs.gz') 


cruentus <- cruenuts_AF %>%
  mutate(mAF=case_when(unknownEM > 0.5 ~ 1-unknownEM,
                      TRUE~ unknownEM))

```



```{r}
  caudatus_tests<-fread('/Users/josedias/mount/scratch/jgoncal1/outputs/caudatus_tests.bedgraph') %>%
          dplyr::rename(CHR=V1, StartPos=V2, EndPos=V3, tW=V4, tP=V5, Tajima=V6, nSites=V7) %>%
  mutate(Watterson=tW/nSites, pi=tP/nSites, TajimaPerSite=Tajima/nSites, species = "caudatus")
  

cruentus_tests<-fread('/Users/josedias/mount/scratch/jgoncal1/outputs/crunetus_tests.bedgraph')  %>%
          dplyr::rename(CHR=V1, StartPos=V2, EndPos=V3, tW=V4, tP=V5, Tajima=V6, nSites=V7) %>%
  mutate(Watterson=tW/nSites, pi=tP/nSites, TajimaPerSite=Tajima/nSites, species = "cruentus")

hybridus_tests<-fread('/Users/josedias/mount/scratch/jgoncal1/outputs/hybridus_tests.bedgraph') %>%
          dplyr::rename(CHR=V1, StartPos=V2, EndPos=V3, tW=V4, tP=V5, Tajima=V6, nSites=V7) %>%
  mutate(Watterson=tW/nSites, pi=tP/nSites, TajimaPerSite=Tajima/nSites, species="hybridus")

hypochondriacus_tests<-fread('/Users/josedias/mount/scratch/jgoncal1/outputs/remake_hypochondriacus_tests.bedgraph') %>%
          dplyr::rename(CHR=V1, StartPos=V2, EndPos=V3, tW=V4, tP=V5, Tajima=V6, nSites=V7) %>%
  mutate(Watterson=tW/nSites, pi=tP/nSites, TajimaPerSite=Tajima/nSites, species="hypochondriacus")

quitensis_tests<-fread('/Users/josedias/mount/scratch/jgoncal1/outputs/confirmation_quitensis_tests.bedgraph') %>%
          dplyr::rename(CHR=V1, StartPos=V2, EndPos=V3, tW=V4, tP=V5, Tajima=V6, nSites=V7) %>%
  mutate(Watterson=tW/nSites, pi=tP/nSites, TajimaPerSite=Tajima/nSites, species="quitensis")
```




```{r}
all_species.filtered <- full_join(caudatus_tests, cruentus_tests) %>%
  full_join(quitensis_tests) %>%
  full_join(hybridus_tests) %>%
  full_join(hypochondriacus_tests) %>%
  full_join(quitensis_tests) %>%
    filter(nSites>250)


all_species.filtered %>%
    group_by(species) %>%
summarise_if(is.numeric, mean)



    

  plot_Tajima_all_species_filtered<-            ggplot(all_species.filtered, aes(x=Tajima)) +
geom_density(aes(color = species, fill=species), alpha=0.4) +
nice_layout +
           labs(title = "Tajima")
      
      
             plot_pi_all_species_filtered<- ggplot(all_species.filtered, aes(x=pi)) +
geom_density(aes(color = species, fill=species), alpha=0.4) +
nice_layout +
        labs(title = "pi")

                   
             plot_Watterson_all_species_filtered<-     ggplot(all_species.filtered, aes(x=Watterson)) +
geom_density(aes(color = species, fill=species), alpha=0.4) +
nice_layout      +     
           labs(title = "Watterson")
           
         
           
title.filtered <- ggdraw() + 
draw_label(
"All species nsites >250",
fontface = 'bold',
x = 0,
hjust = 0
) 

plot_grid(plot_Tajima_all_species_filtered, plot_pi_all_species_filtered, plot_Watterson_all_species_filtered, labels="AUTO", title.filtered)



```


```{r}



ratio_cau_hyb<-caudatus_tests %>%
  filter(nSites>250) %>%
full_join(hybridus_tests, by = c("CHR", "StartPos", "EndPos")) %>%
  mutate(ratio_cau_hyb=pi.x/pi.y) %>%
select(CHR, StartPos, EndPos, ratio_cau_hyb)

ratio_cru_hyb<- cruentus_tests %>%
    filter(nSites>250) %>%

full_join(hybridus_tests, by = c("CHR", "StartPos", "EndPos")) %>%
  mutate(ratio_cru_hyb=pi.x/pi.y) %>%
  select(CHR, StartPos, EndPos, ratio_cru_hyb)


ratio_hyp_hyb<- hypochondriacus_tests %>%
    filter(nSites>250) %>%

full_join(hybridus_tests, by = c("CHR", "StartPos", "EndPos")) %>%
  mutate(ratio_hyp_hyb=pi.x/pi.y) %>%
  select(CHR, StartPos, EndPos, ratio_hyp_hyb)



ratio_qui_hyb<- quitensis_tests %>%
    filter(nSites>250) %>%
full_join(hybridus_tests, by = c("CHR", "StartPos", "EndPos")) %>%
  mutate(ratio_qui_hyb=pi.x/pi.y) %>%
      select(CHR, StartPos, EndPos, ratio_qui_hyb)


ratio_cau_qui<- caudatus_tests %>%
    filter(nSites>250) %>%

full_join(quitensis_tests, by = c("CHR", "StartPos", "EndPos")) %>%
  mutate(ratio_cau_qui=pi.x/pi.y) %>%
  select(CHR, StartPos, EndPos, ratio_cau_qui)



ratio_hyp_qui<- hypochondriacus_tests %>%
    filter(nSites>250) %>%
full_join(quitensis_tests, by = c("CHR", "StartPos", "EndPos")) %>%
  mutate(ratio_hyp_qui=pi.x/pi.y) %>%
  select(CHR, StartPos, EndPos, ratio_hyp_qui)



ratios<- full_join(ratio_cau_hyb, ratio_cru_hyb) %>%
  full_join(ratio_hyp_hyb) %>%
  full_join(ratio_cau_qui) %>%
  full_join(ratio_qui_hyb) 
ratios

ratios %>%
  na.exclude() %>%
summarise_if(is.numeric, mean)


quitensis_tests %>%
  select(CHR, StartPos, EndPos, Watterson) %>%
fwrite("/Users/josedias/mount/scratch/jgoncal1/outputs/quitensis_WattersonTheta", quote=FALSE, sep='\t')


```


